name: example
description: "example for flutter_linear_calendar"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    flutter_linear_calendar: ^latest