name: flutter_linear_calendar
description: "A reusable horizontal date selector widget for Flutter."
version: 2.0.0
repository: "https://github.com/PearlGrell/flutter_linear_calendar"

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0